server:
  forward-headers-strategy: framework  # enable x-forwarding
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      forwarded:
        enabled: true # enable x-forwarding
    consul:
      discovery:
        register: false
        register-health-check: false
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.int[1,999999]}
      host: consul
