server:
  forward-headers-strategy: framework  # enable x-forwarding
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # must be false for x-forwarded to work
      forwarded:
        enabled: true # enable x-forwarding
