server:
  forward-headers-strategy: framework  # enable x-forwarding
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        register: false
        register-health-check: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # must be false for x-forwarded to work
      forwarded:
        enabled: true # enable x-forwarding for spring-apidocs
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
           - Path=/auth/**  # convert path to just /register or sign-up &  /login
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
#            - TokenRelay=
