server:
  port: 8088
spring:
  application:
    name: gateway
  config:
    import: optional:consul:consul:8500
  cloud:
    consul:
      discovery:
        register: false
        register-health-check: false
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.int[1,999999]}
      host: localhost
      config:
        enabled: true
        format: yaml
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: registration
          uri: lb://authentication
          predicates:
           - Path=/sign-up
           - Method=POST
          filters:
            - RewritePath=/sign-up, /register

        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /authenticate

        - id: url-shortener
          uri: lb://url-shortener
          predicates:
            - Path=/url/**
          filters:
              - RewritePath=/url/(?<path>.*), /$\{path}

        - id: get-individual-shortened-url
          uri: lb://url-shortener
          predicates:
            - Path=/urls/**
          filters:
              - RewritePath=/urls/(?<path>.*), /s/$\{path}

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/images/**
          filters:
            - RewritePath=/images/(?<path>.*), /images/$\{path}
