server:
  forward-headers-strategy: framework  # enable x-forwarding
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        register: false
        register-health-check: false
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.int[1,999999]}
      host: consul
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      forwarded:
        enabled: true # enable x-forwarding for spring-apidocs
      routes:
        - id: registration
          uri: lb://authentication
          predicates:
           - Path=/sign-up
          filters:
            - RewritePath=/sign-up, /register
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /authenticate

#          filters:
#            - RewritePath=/auth/(?<path>.*), /$\{path}
#            - TokenRelay=
